### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'cfg_path' and 'cfg_name'

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev_template#104]
# How to reproduce
1. new repo based off of template
2. update `settings.ini` to match personal repo and user
3. update `index.ipynb` so that `your_lib_name` is `lib_name` from `settings.ini`
4. run `nbdev_install_git_hooks` 
5. run `nbdev_clean_nbs`
6. run `nbdev_build_lib && nbdev_build_docs`
7. get error

**Comment by dsm-72** [comment]
```
Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/ml/bin/nbdev_build_lib", line 10, in <module>
    sys.exit(nbdev_build_lib())
  File "/home/USER/anaconda3/envs/ml/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/USER/anaconda3/envs/ml/lib/python3.9/site-packages/nbdev/export2html.py", line 477, in nbdev_build_lib
    write_tmpls()
  File "/home/USER/anaconda3/envs/ml/lib/python3.9/site-packages/nbdev/export2html.py", line 467, in write_tmpls
    cfg = Config()
TypeError: __init__() missing 2 required positional arguments: 'cfg_path' and 'cfg_name'
```

**Comment by dsm-72** [comment]
@muellerzr any idea?

**Comment by muellerzr** [comment]
Upgrade your fastcore?

**Comment by dsm-72** [comment]
@muellerzr how do I do that?

**Comment by dsm-72** [comment]
@muellerzr ok, I ran `conda update fastcore` and I still get the same error

**Comment by muellerzr** [comment]
What is the fastcore currently installed and nbdev installed?

pip show fastcore nbdev

**Comment by dsm-72** [comment]
Fastcore was up to date. However `nbcovert` was `5.5.0` and `nbdev` was `1.1.5` and `conda update nbdev` didn't run. So I forced it with `conda install -c fastai nbdev=1.2.10` and now I get:

```
Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/ml/bin/nbdev_build_lib", line 7, in <module>
    from nbdev.export2html import nbdev_build_lib
  File "/home/USER/anaconda3/envs/ml/lib/python3.9/site-packages/nbdev/export2html.py", line 15, in <module>
    from .showdoc import *
  File "/home/USER/anaconda3/envs/ml/lib/python3.9/site-packages/nbdev/showdoc.py", line 12, in <module>
    from fastcore.docments import _docments, isclass, _clean_comment, _tokens, _param_locs, _get_comment
ImportError: cannot import name '_docments' from 'fastcore.docments' (/home/USER/anaconda3/envs/ml/lib/python3.9/site-packages/fastcore/docments.py)
```

@muellerzr

**Comment by dsm-72** [comment]
```
fastcore  1.4.4
nbconvert 6.4.4
nbdev     1.2.10
```

**Comment by muellerzr** [comment]
You need 1.4.5. @jph00 was that released on conda?

For the time being do pip install fastcore -U

**Comment by dsm-72** [comment]
How do I do that?

**Comment by jph00** [comment]
https://anaconda.org/fastchan/fastcoreMessage ID: ***@***.***>
