### ISSUE TITLE
Fresh install Github action failure

### ISSUE THREAD

**Issue by dharmeshkakadia** [fastai/nbdev_template#23]
Fresh use of the template, failed the first CI run on the initial commit. Any pointers? 

Repo https://github.com/dharmeshkakadia/nbdev_playground/

```
ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.6.12/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/runner/work/nbdev_playground/nbdev_playground/setup.py'"'"'; __file__='"'"'/home/runner/work/nbdev_playground/nbdev_playground/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vc3tavs9
         cwd: /home/runner/work/nbdev_playground/nbdev_playground/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/runner/work/nbdev_playground/nbdev_playground/setup.py", line 13, in <module>
        for o in expected: assert o in cfg, "missing expected setting: {}".format(o)
    AssertionError: missing expected setting: description
```

**Comment by dharmeshkakadia** [comment]
Oh. I didnt realize, this is expected and I need to update my settings.ini as the first thing. Sorry, about that. The error went away after I updates settings. 
I think it would be good to add this in the documentation. Happy to send PR if you think it would be a good idea.
