### ISSUE TITLE
building docs following tutorial fails, no file called core

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev_template#99]
```
Converted 00_core.ipynb.
Converted index.ipynb.
converting: /Users/sumner/Projects/sugar/00_core.ipynb
converting: /Users/sumner/Projects/sugar/index.ipynb
'HTMLExporter' object has no attribute 'template_path'
'HTMLExporter' object has no attribute 'template_path'
Conversion failed on the following:
00_core.ipynb
index.ipynb
Traceback (most recent call last):
  File "/Users/sumner/miniforge3/bin/nbdev_build_docs", line 8, in <module>
    sys.exit(nbdev_build_docs())
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/fastcore/script.py", line 112, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/nbdev/export2html.py", line 643, in nbdev_build_docs
    if fname is None: make_sidebar()
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/nbdev/export2html.py", line 708, in make_sidebar
    create_default_sidebar()
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/nbdev/export2html.py", line 700, in create_default_sidebar
    dic = {get_config().lib_name: _create_default_sidebar()}
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/nbdev/export2html.py", line 692, in _create_default_sidebar
    titles = [_get_title(f) for f in fnames if f.stem!='index']
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/nbdev/export2html.py", line 692, in <listcomp>
    titles = [_get_title(f) for f in fnames if f.stem!='index']
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/nbdev/export2html.py", line 682, in _get_title
    with open(fname, 'r') as f: code = f.read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sumner/Projects/sugar/docs/core.html'

```

**Comment by dsm-72** [comment]
@muellerzr any update?

**Comment by hamelsmu** [comment]
Not able to reproduce the error from the way the issue was communicated.

Here is a blog article that describes a framework for reporting bugs more effectively that others can act on: http://testthewebforward.org/docs/bugs.html

**Comment by dsm-72** [comment]
@hamelsmu this happens sometimes with the following setup. Let `repo` be the name of the nbdev project. Then in the directory `repo/repo` (the python package built via nbdev_build_lib) if there are no files, `nbdev_build_lib` fails
